### ISSUE TITLE
Duplicate Home Assistant services getting spawned in 108.3 container

### ISSUE THREAD

**Issue by mstanislav** [home-assistant/docker#113]
I've recently loaded up 108.3 using the official HA image and started to run into ZWave issues. Turns out there was an exclusive lock issue for the `/dev/ttyUSB0` device. Looking into this further, I found the following inside of my running container...
```
226 root      0:54 python3 -m homeassistant --config /config
251 root      0:40 python -m homeassistant --config /config
```
I can see with `lsof` on the host that there are indeed two Python processes which are accessing that device. I took a quick glance at more recent commits and see some changes with s6 that at least made me wonder if there's something here with the supervisor spawning the duplicated processes?

[This HA forum post](https://community.home-assistant.io/t/synology-docker-two-problems-after-update-to-latest-version/184213) seems to represent some other folks who may have this issue. Sorry if this is a red herring, but seemed worth posting here best I could tell.

**Comment by frenck** [comment]
This is caused by overriding the Docker entry point or Docker command for this container.

In Home Assistant 0.107, we have switch to the use of the S6 Overlay init system to manage the processes we have in our Docker containers. If you previously used to override the command, it may now indeed cause a duplicate instance to be run.

We are aware now that some Docker management systems override by default (Portainer is a known one). This is a bug in those systems, as they are supposed to use the default of the Docker container unless overridden.

Nevertheless, make sure you have not overridden the entry point and/or command.
If you do want to override them, these are the new ones:

- entry point: `/init`
- command (CMD): `` _(empty / not used anymore)_.
