### ISSUE TITLE
udevd daemon don't start on new S6 overlay

### ISSUE THREAD

**Issue by flexy2dd** [home-assistant/docker#117]
**Home Assistant release with the issue:**
109.6

**Operating environment:**
docker on Synology NAS on root

**Hardware context:**
I have two USB stick attached on my Synology one for ZWave and another one for Zigbee

I've recently loaded up 109.6 using the official HA image and started to run into ZWave issues. 
Indeed if NAS restart the usb mount point can be changed (once the ZWave is on the ttyACM0 another time on the ttyACM1 and inversely for the Zigbee).
for this reason I'm forced to go through the serial by-id mount point.

But the udevd daemon doesn't seem to start (/etc/cont-init.d/udev.sh)
If i lauch commands in manual 
`udevd --daemon`
`udevadm trigger`

the _/dev/serial/by-id_ is successfully created

if y try to launch /etc/cont-init.d/udev.sh directly i have **/etc/cont-init.d/udev.sh: Permission denied** error i make a whoami for getting current user and i'm right in root.

make 
`ls -la /etc/cont-init.d/udev.sh`
`-rw-r--r--    1 root     root           304 Apr 29 12:24 /etc/cont-init.d/udev.sh`
and it seems I don't have the right of execution.

**Comment by frenck** [comment]
It doesn't need execution permissions.

This generally happens when one overrides the CMD or ENTRYPOINT of the Docker container. Especially on Synology, which tends to read the defaults and overrides them permanently. Make sure you set not CMD. If we detect a CMD is set, the init system will not start (to prevent multiple instances of Home Assistant for example).

**Comment by flexy2dd** [comment]
Indeed i updated the image, but the old init was still there.
I flush image and recreate form scratch and work great :)
thanks !
